### ISSUE TITLE
오인규의 15팀 리뷰

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/cashbook-15#39]
코드 너무 좋습니다~

#26 서버쪽 코드가 특히 좋네요

제안사항: 리드미가 좀 허전하네요 ㅎㅎ 리드미를 채워주시면 좋을것같습니다

제안사항: 이슈나 풀리퀘스트 템플릿 추가하면 좋더라구요

**Comment by hwookim** [comment]
빠른 시일 내에 리드미를 꾸며보도록 하겠습니다!
