### ISSUE TITLE
localhost:3000으로 리다이렉팅되어 깃헙 로그인이 진행되지 않는 문제 해결

### ISSUE THREAD

**Issue by hwookim** [woowa-techcamp-2021/cashbook-15#48]
깃헙 로그인 시 localhost로 보내 문제가 생김
<img width="1502" alt="스크린샷 2021-08-02 오후 8 22 10" src="https://user-images.githubusercontent.com/45786387/127854117-d550eab0-b5d3-4ccd-bb18-e3b64b821cb5.png">

### 작업 내용
- [x] 깃헙 로그인 시 리다이렉트 주소 수정

**Comment by jigglypop** [comment]
잘된다니 다행이네요 수고많으셨습니다

**Comment by hwookim** [comment]
배포용 깃헙 Ouath Application 등록으로 해결
